require("config.colorscheme")
require("config.lualine")
require("config.options")
require("config.treesitter")
require("config.treesitter_context")
require("config.keymaps")
require("config.lsp")
require("config.which_key")
